crunchyroll/ef-open

build
src/BUILD
src/ef-resolve-config.py

Ready
- build change:
-- rename files w/o ".pex" suffix after successful build
improvements to ef-resolve-config:
- needs boto3 lib
- fix glitch in deriving parameter file path

better config file handling

---

doc/installing-pants-and-building-ef-open.md

ran into a java error on building ef-open tools because it wasn't installed on my local environment. probably worth specifying this prerequisite in the docs

Adding java as a prereq

---

src/ef_app_config_reader.py
src/ef_service_registry.py

**Ready**
* remove logger requirement for init of ef_app_config_reader
* add message for exceptions thrown when service registry is malformed

Streamline config reader

---

src/ef-cf.py

**Ready**
ef-cf will need to also render lookups in parameter files now that encrypted secrets will be stored there (requiring a call to kms). 
- Move template rendering and validation to separate function
- Render templates and parameters using resolve_template()
Updated service proto0 param file to include a "DbPassParam" key with a "{{aws:kms:decrypt,...}}" value. 
```
± |CXOPS-3234 {4} U:5 ?:3 ✗| → ../ef-open/src/ef-cf.py cloudformation/services/templates/myservice.json proto0 --devel --verbose
not refreshing repo because --devel was set or running on Jenkins
service_name: myservice
env: proto0
env_full: proto0
env_short: proto
template_file: cloudformation/services/templates/myservice.json …
```

ef-cf: render parameter files

---

.github/PULL_REQUEST_TEMPLATE.md

Jira: OPS-7442
Reviewer:
PR: GH-24
**Ready**
Reflect JIRA project consolidation
[OPS-7442](https://ellation.atlassian.net/browse/OPS-7442)
Change all references to CXOPS to OPS
[ellation_formation PR-1481](https://github.com/crunchyroll/ellation_formation/pull/1481)

OPS-7442 - JIRA project consolidation

---

src/ef-version.py

**Ready**
Fix ef_version precheck function when versioning services for the first time
* ef-version precheck for dist-hash use to fail when the service never existed in the s3 version bucket, properly catch the error when the key does not exist in the s3 bucket and proceed with the creation of the object if it does not exist.
Before fix:
```
000377-ml:ellation_formation jwong$ ef-version --set 698bdd738d84cb39eb22115bc7f47d01247ec64b  --build 61 --commit_hash 698bdd738d84cb39eb22115bc7f47d01247ec64b --location https://s3-us-west-2.amazonaws.com/ellation-cx-proto3-static/chromecast/dist-hash chromecast dist-hash proto3 --devel --verbose
precheck_dist_hash with key: chromecast/proto3/dist-hash
Precheck failed: An error occurred (NoSuchKey) when calling the GetObject operation: The specified …
```

Fix ef_version precheck function when versioning services for the first time

---

src/ef-generate.py
src/ef_template_resolver.py

**Ready**
Add instance profile support

Instance profile support

---

plugins_available/newrelic/interface.py

**Ready**
This is to fix a break in ef-generate. Once we created enough alert policies to start getting paginated responses it broke our integration with newrelic. This update will make the newrelic iterate through all paginated get requests.  
- add iterative_get() to Newrelic class
- make all gets to newrelic run through the new method
```
± |master {4} S:1 U:3 ?:1 ✗| → ef-generate staging --commit
env: staging
env_full: staging
env_short: staging
aws account profile: ellationeng
aws account number: 366843697376
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): kms.us-west-2.amazonaws.com
exit: success
```

iterate through paginated newrelic responses

---

src/ef_aws_resolver.py

**Ready**
The existing regex for EIP resources is crazy restrictive. This loosens it up a bit.
- Update eip resource regex
https://github.com/crunchyroll/ellation_formation/pull/2063
tested on partners-sftp in staging

less restrictive regex for naming conventions

---

src/ef-generate.py

**Ready**
[OPS-9007](https://ellation.atlassian.net/browse/OPS-9007)
- prevent VPC related resources from being created in global

prevent VPC related resources from being created in global

---

src/BUILD
src/ef_config.py

**Ready**
[OPS-9327](https://ellation.atlassian.net/browse/OPS-9327)
- add yaml as dependency to builds
- add ef_repo to EFConfig
[PR 45](https://github.com/crunchyroll/ef-open/pull/45)

Ops 9327 b

---

src/BUILD

**Ready**
include ef_site_config

remove exclude statement

---

doc/setup-and-configuration.md
doc/symbol-reference.md

**Ready**
Update setup documentation
* Added required python dev libraries
* Added required environment variable `EF_SITE_REPO`

Update setup documentation

---

README.md
setup.py
tests/unit_tests/context_paths.py
tests/unit_tests/test_ef_generate.py
tests/unit_tests/test_ef_password.py
tests/unit_tests/test_ef_version.py

**Ready**
- Repairing the unit tests (incorrect paths and module names)
- Adding README instructions for running tests
- Adding dev/test dependencies to the setup.py

Working unit tests, add unit test dependencies to setup.py, and README for testing

---

efopen/ef_aws_resolver.py

**Ready**
Small code reduction for cognito lookup
[OPS-10906](https://ellation.atlassian.net/browse/OPS-10906)
Tested in ellationeng.

OPS-10906-v3  Reduce if statement condition for cognito lookup

---

Pipfile
Pipfile.lock

**Ready**
Create pipfile which defines a development virtualenv

add pipfile for local development

---

tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Updated unit tests for the 4th time.
[OPS-10906](https://ellation.atlassian.net/browse/OPS-10906)

OPS-10906-v4 Updated unit tests for the 4th time.

---

Pipfile.lock
efopen/ef_cf.py
setup.py

**Ready**
Adds a `--lint` flag to ef-cf which runs cfn-lint on the rendered template. This will be used in our ellation_formation ci pipeline. 
```
(ef-open) bash-4.4$ ef-cf cloudformation/services/templates/subs-events.json proto0 --lint
not refreshing repo because --devel was set or running on Jenkins
=== LINTING ===
W3005 Obsolete DependsOn on resource (EventsStreamCr), dependency already enforced by a "Fn:GetAtt" at Resources/EventsFirehoseCr/Properties/KinesisStreamSourceConfiguration/KinesisStreamARN/Fn::GetAtt/['EventsStreamCr', 'Arn']
.lint/template.json:92:7
W3005 Obsolete DependsOn on resource (EventsStreamVrv), dependency already enforced by a "Fn:GetAtt" at …
```

ef-cf --lint

---

efopen/ef_cf.py

**Ready**
Add CAPABILITY_NAMED_IAM to ef-cf
* Add CAPABILITY_NAMED_IAM to ef-cf

Add CAPABILITY_NAMED_IAM to ef-cf

---

efopen/ef_cf.py

**Ready**
Added CAPABILITY_AUTO_EXPAND to enable use of cloudformation macros in our templates.
[OPS-11289](https://ellation.atlassian.net/browse/OPS-11289)
Tested in alpha0 with Jeff Milberger's stack.

OPS-11289 Added CAPABILITY_AUTO_EXPAND 

---

tests/test_data/ef_site_config.yml

**Ready**
Need to update ef_site_config.yml in the ef-open project so the unit tests pass for the new feature.
[OPS-11361](https://ellation.atlassian.net/browse/OPS-11361)

OPS-11361-v2 Make unit tests pass again

---

efopen/ef_cf_diff.py

**Ready**
Improve the logging output to include the service type (fixtures, application_services, etc)

specify the service type in the INFO outout

---

efopen/ef_cf.py

**Ready**
Hotfix for checking autoscaling properties
- check for autoscaling properties before getting current desired

Check autoscaling_group_properties for None

---

.github/PULL_REQUEST_TEMPLATE.md
efopen/ef_conf_utils.py
tests/unit_tests/test_ef_conf_utils.py

**Ready**
Fix regex and regex tests for ef_conf_utils.py pull_repo. Not sure wh…y this started to blowup but now it is.
[OPS-13555](https://ellation.atlassian.net/browse/OPS-13555)
Unit tests passed

OPS-13555-v2 Fix pull_repo regex error

---

efopen/ef_version.py

**Ready**
[OPS-13631](https://ellation.atlassian.net/browse/OPS-13631)
Take out println causing pipelines to fail because of unexpected output

OPS-13631-v2 takeout print statement

---

Pipfile.lock

**Ready**
mostly just to keep cfn-lint up to date.

ran: pipenv update --dev

---

efopen/ef_service_registry.py

revert the attempt to make the world better

---

efopen/ef_cf.py

**Ready**
[OPS-13829](https://ellation.atlassian.net/browse/OPS-13829)
calculate_max_batch_size must at least return a 1 or higher

OPS-13829 calculate_max_batch_size must at least return a 1 or higher

---

efopen/ef_cf.py
efopen/ef_cf_diff.py
efopen/ef_check_config.py
efopen/ef_generate.py
efopen/ef_password.py
efopen/ef_version.py

**Ready**
[OPS-11791](https://ellation.atlassian.net/browse/OPS-11791)
Add a description for the following ef-open tools

OPS-11791 Add a description for the following ef-open tools

---

efopen/ef_cf.py

Ready State and Ticket
**Ready**
[OPS-14859](https://ellation.atlassian.net/browse/OPS-14859)
change how it checks if the autoscalinggroup resource has an UpdatePolicy element

OPS-14859 Update ef-cf check on UpdatePolicy in autoscalingroup

---

efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

> Valid states are:
> Ready - This PR is ready to be reviewed.
> Not Ready - Please provide an explanation below.
**Ready**
[ESS-2824](https://ellation.atlassian.net/browse/ESS-2824)
> A description of the motivation and implementation of this PR.
> Include any relevant details like:
> - Test results
> - Unusual deployment requirements
> - Current deployed state, if any
> - General issues for discussion during the review
To use VPC Endpoints without turning on Private DNS, we need a means of fetching their DNS names.

Adds ability to fetch VPC Endpoint DNS names

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-15043](https://ellation.atlassian.net/browse/OPS-15043)
Update the new relic executor and interface code to support generating the nrql alert conditions.
Also did some cleanup of the code due to poor choice of variable names, methods

OPS-15043 Update ef-generate to create new nrql alert conditions for instance-init failures

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

**Ready**
[OPS-15207](https://ellation.atlassian.net/browse/OPS-15207)
Update ef-open to handle nrql alert conditions. Note that the new changes have already been used to implement nrql alert conditions for staging.

OPS-15207 Update efopen for nrql conditions

---

efopen/ef_generate.py

**Ready**
Only enable KMS key rotation on commit flag
* Only enable KMS key rotation on commit flag
Ran ef-generate on proto0

Only enable KMS key rotation on commit flag

---

efopen/newrelic_executor.py

[OPS-15195](https://ellation.atlassian.net/browse/OPS-15195)
missing the aws_ecs_http

OPS-15195-v2 missing one of the ecs types

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-15473](https://ellation.atlassian.net/browse/OPS-15473)
We want to have all our auto created policies pinging the services teams in OpsGenie.
For every policy:
- check if an OpsGenie notification channel for the team exists
- if it doesn't exist, create one
- subscribe the OpsGenie channel to the policy

OPS-15473 Tie NR policies to OG teams

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-15474](https://ellation.atlassian.net/browse/OPS-15474)
Automate APM/Browser alert conditions using the definition from ef_site_config.yml
Should be merged after ef_site_config.yml is merged into master.

OPS-15474 Automate APM alerts creation

---

efopen/newrelic_executor.py

Follow-up from PR https://github.com/crunchyroll/ef-open/pull/194, remove account name from ef-open code to make conditional more agnostic.

Opsgenie prod only

---

efopen/ef_config.py

[OPS-15640](https://ellation.atlassian.net/browse/OPS-15640)
Add lambda functions versioning in order to automate lambda@edge deployment.

OPS-15640 Add version of lambda functions

---

efopen/newrelic_executor.py

[OPS-15659](https://ellation.atlassian.net/browse/OPS-15659X)
Automate AWS Lambda alerts creation using the most important metrics.
See https://github.com/crunchyroll/ellation_formation/pull/7712

OPS-15659 Automate lambda functions alerts creation

---

efopen/ef_context.py
efopen/ef_generate.py

Run ef-generate for only a specific entry in the service_registry. We have to do this occasionally and it's always painful having to wait for a full run.

ef-generate --only

---

efopen/ef_cf.py

[OPS-15648](https://ellation.atlassian.net/browse/OPS-15648)
In order to avoid regex parsing of unresolved CF template, add option that takes a directory that contains `cfn-lint` custom rules that helps writing better CI tests for infrastructure code.
```
➜  ef-cf --lint cloudformation_template.json prod --devel
=== CLOUDFORMATION LINTING ===
Template passed CFN linting
➜  ef-cf --lint --custom_rules=./tests/rules cloudformation_template.json prod --devel
=== CLOUDFORMATION LINTING ===
E3601 Encryption should be configured by default for S3Bucket …
```

OPS-15648 Add functionality to add custom rules for cfn-lint

---

efopen/newrelic_executor.py

[OPS-16137](https://ellation.atlassian.net/browse/OPS-16137)
Remove the 4xx cloudfront errors from ef-generate

OPS-16137-Do not spam with 4xx CF errors in #alerts Slack channel

---

setup.py

[OPS-15990](https://jira.tenkasu.net/browse/OPS-15990)
Pin all versions of dependencies to avoid any future inconsistencies.

OPS-15990 Fix version of ef-open dependencies

---

efopen/ef_aws_resolver.py

[OPS-16439](https://ellation.atlassian.net/browse/OPS-16439)
In order to be able to use IP Lists within multiple rules, we need to be able to look them up by their human readable names.

OPS-16439 Add WAF IPSet lookup

---

Pipfile.lock
efopen/newrelic_interface.py
setup.py

We've been having issues with NewRelic returning 503 errors and ef-generate failing when creating alerts. I'm unsure of the nature of the issues, but I found that retrying the action helps and allows ef-generate to successfully create all of our alerts.

Exponential retry for NewRelic actions

---

.github/workflows/gitleaks.yml
.github/workflows/slack-notify.yml

Create a notification in DevOps slack when a new pull request is opened/reopened

OPS-16624 Add PR Notifications to Devops slack channel

---

efopen/ef_config.py
efopen/ef_version.py

This reverts commit 8f1d1137171c14d343756c4bbac016aa9e4dc47f.

Revert "OPS-16623 add pipeline build number option (#222)"

---

efopen/ef_config.py
efopen/ef_version.py

[OPS-16623](https://ellation.atlassian.net/browse/OPS-16623)
> A description of the motivation and implementation of this PR.
> Include any relevant details like:
> - Test results
> - Unusual deployment requirements
> - Current deployed state, if any
> - General issues for discussion during the review

Ops 16623 rollback pipeline

---

.github/workflows/semgrep.yml

COM-1336
Adds the following semgrep configs:
- p/python
- p/bandit
- p/ci
- p/secrets
- r/contrib.dlint
- r/python.requests

Add semgrep github action

---

efopen/ef_aws_resolver.py
setup.py

OPS-17899
Adds a lookup to dynamically retrieve Cloudflare IPs for whitelisting in WAFv1 and WAFv2
I believe that this is the first ef-open AWS lookup to return something other than a string. As such, we need to be careful not to wrap this lookup in quotes like we do with others. So ignore your IDE's JSON linter here. 
Created a test cloudformation with the lookup, and validated that all Cloudflare IPs are contained in the template output. 
**Test Template**
```
{
"AWSTemplateFormatVersion": "2010-09-09",
"Description": "global-waf",
"Conditions": {
"EnvIsGlobalEllationeng": { "Fn::Equals": [ "{{ENV_FULL}}", "global.ellationeng" ] }
},
"Resources": {
"CloudflareCidrTest": {
"Type": "AWS::WAF::IPSet",
"Properties": {
"IPSetDescriptors": {{aws:waf:cloudflare/ip-list}},
"Name": …
```

OPS-17899 add cloudflare IP lookup

---

.github/PULL_REQUEST_TEMPLATE.md

[OPS-19267](https://jira.tenkasu.net/browse/OPS-19267)
> This PR creates a unified pull request template for all Devops repos.

Create / Update pull_request_template

---

efopen/ef_cf.py

Adds an optional `--high_load` parameter to `ef-cf`. This will deploy the service while leveraging a high-load parameters override file, if present. If not, it will exit gracefully.

[draft] [PLAT-1303] add a high_load parameter for override parameters files

---

setup.py

Fix dateutil version to 2.8.2
