crunchyroll/ef-open

pylintrc
src/ef-version.py
src/ef_config.py
src/ef_version_resolver.py

**Ready**
Simplify version resolver to strictly get versions from the version bucket. 
Reference resolution moves to ef-version. This means that references are no longer written to the version bucket and instead are immediately resolved to the respective ami-id which is then written to the bucket. 
* add pylintrc
* Version lookups no longer support a recurse switch
* VERSION_KEYS moves into ef_config

Always resolve version

---

getting-started/ef_site_config.py
src/ef_config.py
src/ef_config_resolver.py
src/ef_context.py
src/ef_service_registry.py
src/ef_template_resolver.py
src/ef_utils.py

**Ready**
Dynamically resolve environment list and quantity of env replicas based on ENV_ACCOUNT_MAP in ef_site_config. This offloads values from ef_config that are more appropriately set in ef_site_config. 
This is effectively one approach to solving the issue and is up for discussion.
* dynamically resolve ENV_LIST and VALID_ENV_REGEX
* update example
* introduce protected and ephemeral envs
```
toverton:~/Documents/Ellation/dev/ef-open dynamic-env-resolution $ python ./src/test_ef_aws_resolver.py
................................................
----------------------------------------------------------------------
Ran 48 tests in 12.306s
OK
toverton:~/Documents/Ellation/dev/ef-open dynamic-env-resolution $ python ./src/test_ef_config_resolver.py
. …
```

Dynamic env resolution

---

.github/PULL_REQUEST_TEMPLATE.md

Easier than cut-n-pasting the [Pull Request Description Template](https://ellation.atlassian.net/wiki/display/DEVOPS/Contributing#Contributing-PullRequestDescriptionTemplate) every time
As discussed in [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates) and documented in [Helping people contribute to your project](https://help.github.com/articles/helping-people-contribute-to-your-project/) / [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

Provide PR template

---

doc/installing-pants-and-building-ef-open.md
src/BUILD
src/ef-password.py
src/ef_utils.py
tests/unit_tests/test_ef_password.py
tests/unit_tests/test_ef_utils.py

**Ready**
Final PR for the secure credentials project. Adds the ef-password utility and test coverage. 
[CXOPS-3057](https://ellation.atlassian.net/browse/CXOPS-3057)
- ef-password util
- unit and integration tests for ef-password
- unit tests for kms functions recently added to ef_utils
- fixing small type error bug in ef_utils
```
○ → ./pants binary ef-open/src:
fatal: Not a git repository (or any of the parent directories): .git
16:41:28 00:00 [main]
(To run a reporting server: ./pants server)
16:41:28 00:00   [setup]
16:41:28 00:00     [parse]fatal: Not a git repository (or any of the parent directories): .git
Executing tasks in goals: bootstrap -> imports -> unpack-jars -> deferred-sources -> gen -> jvm-platform-validate -> resolve -> compile -> resources -> binary
16:41:28 00:00 …
```

EF-Password

---

getting-started/ef_site_config.py
src/ef-instanceinit.py
src/ef_config.py

**Ready**
Change local dev env name from a hardcoded value ("localvm") to a variable stored in ef_site_config
[CXOPS-3246](https://ellation.atlassian.net/browse/CXOPS-3246)
- Update template resolver env param to use value from site config
- Include value in template site config file (getting-started/ef_site_config.py)
- Remove unused attribute from EFConfig class
- Small formatting updates to ef-instanceinit.py
https://github.com/crunchyroll/ellation_formation/pull/1436
```
[root@data-api vagrant]# python /usr/local/bin/ef-instanceinit
...
next item: '/vagrant/configs/data-api/templates/data-api.yaml'
checking: /vagrant/configs/data-api/templates/data-api.yaml
Loading parameters file: /vagrant/configs/data-api/templates/data-api.yaml
Resolving template
Loading template file: …
```

ef-instanceinit localdev

---

src/ef-generate.py
src/ef_utils.py
tests/unit_tests/test_ef_generate.py
tests/unit_tests/test_ef_password.py
tests/unit_tests/test_ef_utils.py

**Ready**
KMS does not allow periods in key alias names which breaks when generating keys for subservices ([kms alias doc](http://docs.aws.amazon.com/kms/latest/APIReference/API_CreateAlias.html)). Updating code to convert all periods to underscores for key aliases. 
[CXOPS-3291](https://ellation.atlassian.net/browse/CXOPS-3291)
- ef-generate to create aliases with an underscore in place of any periods
- ef_utils.kms_encrypt() will try to use an alias with an underscore rather than period when called
- add tests for the above
- env name "test" is no longer valid, updated test_ef_password accordingly
- convert test_ef_generate to two spaces 
```
platform darwin -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /Users/dlutsch/.virtualenvs/etp/bin/python2.7
cachedir: .cache
rootdir: …
```

Update ef-password to accommodate subservices

---

plugins_available/newrelic/README.md
plugins_available/newrelic/config.py
plugins_available/newrelic/executor.py
plugins_available/newrelic/interface.py

**Ready**
Previously the automated newrelic alerts were limited to ec2 instance metrics. This opens it up to work with any kind of metrics/condition. I've added several newrelic metrics to our config in ellation_formation (https://github.com/crunchyroll/ellation_formation/pull/1635)
[OPS-7814](https://ellation.atlassian.net/browse/OPS-7814)
```
/Users/dlutsch/.virtualenvs/etp/bin/python /Users/dlutsch/workspace/ef-open/src/ef-generate.py staging --devel --commit
Not refreshing repo because --devel was set or running on Jenkins
env: staging
env_full: staging
env_short: staging
aws account profile: ellationeng
aws account number: 366843697376
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): kms.us-west-2.amazonaws.com …
```

Allow any kind of newrelic alerts

---

getting-started/ef_site_config.py
src/ef-cf.py

**Ready**
Support polling of the cloudformation stack status in ef-cf. When enabled, ef-cf will block until stack create/update completion or failure. 
- add polling period to example ef_site_config
- add poll argument and support in context
[ellation-formation PR 1720](https://github.com/crunchyroll/ellation_formation/pull/1720)
1. rebuild ef-cf
1. Set a new ami-id using the test-instance
* `$ ef-version test-instance ami-id [ENV] --history text --limit 5`
* `$  ef-version test-instance ami-id [ENV] --set [AMI-ID] --commit --devel`
1. Run ef-cf
* `$ ef-cf cloudformation/services/templates/test-instance.json proto3 --devel --commit --poll --verbose`
* Assert ef-cf reports stack status and finishes on completion of stack update

Cf polling

---

doc/symbol-reference.md
src/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Create a network acl ID lookup for template resolution
[OPS-8526](https://ellation.atlassian.net/browse/OPS-8526)
- update docs with network acl id symbol lookup
- create tests and fix broken tests
- create network acl lookup
- fix logic to add issued date to certs
- return none on lookup attribute errors
- update truncation handling logic
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-3.2.2, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: Users/toverton/Documents/Ellation/dev/ef-open/tests/unit_tests/.cache
rootdir: /Users/toverton/Documents/Ellation/dev/ef-open/tests/unit_tests, inifile:
plugins: cov-2.5.1
collecting ... collected 53 items …

Add Network ACL ID Lookup

---

src/ef-password.py

**Ready**
Per conversation with Jerry, makes ef-password's output be more conducive for quick copy/paste
Changes output to include the lookups for ef template resolver
```
○ → ef-password ece proto0
Generated Secret: kJ4brswtzArzcP9HEzk6XtwACtyZNdcr
{{aws:kms:decrypt,AQICAHistorhvkDyjb0bA1VwGEICk1xFQutt+BaEK+dPBnYxUAGy8WBRoqaNoFOGNG4WTuoLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMm31NUisq6Vn+ylkSAgEQgDsqtOYHqE4Gm9Xgy17gmNAZotn0/6930zcB1kTe8STlov37uWXCtMwWmc6YjGJ99i3th9enqHY0Hl3lnw==}}
```

change output to be more copy/paste friendly

---

src/ef-version.py

**Ready**
Changing ef-version s3 policy to have object be bucket-owner-full-control
* Changing ef-version s3 policy to have object be bucket-owner-full-control

Changing ef-version s3 policy to have object be bucket-owner-full-control

---

src/ef_aws_resolver.py

**Ready**
This will prevent ef-cf from dying when doing an eip lookup on a stack doesn't exist in a given account.
- add try/catch around cloudformation.describe_stack_resources()
Tested locally on my data-looker stack in prod that was failing due to this bug

add try/catch around cloudformation.describe_stack_resources()

---

src/ef-password.py
tests/test_data/test.cnf.parameters.json
tests/unit_tests/test_ef_password.py

**Ready**
Initial commit to support encrypting parameters file with ef-password. This new functionality will allow individuals to have a parameters file containing secret level data where they can call ef-password to encrypt all the contents inside of the file by matching on a certain key.
* Added --secret_file and --match option to ef-password
```
000377-ml:ellation_formation jwong$ cat configs/test-instances/parameters/test.cnf.parameters.json
{
"dest": {
"path": "/srv/test-instances/test.cnf",
"dir_perm": "755",
"file_perm": "644",
"user_group": "wwwuser:wwwuser"
},
"params": {
"default": {
"username": "foobar"
},
"proto0": {
"password": "passwordpassword",
"password1": "mock_test1",
"password2": "mock_test2",
"password3": "mock_test3"
},
"staging": {
"password": "passwordpassword", …
```

Initial commit to support encrypting parameters file with ef-password

---

src/ef_aws_resolver.py

**Ready**
This fixes elasticip lookups that contain the {{ENV}} variable. By convention we capitalize the env in the resource name of the elasticip, however the rendered {{ENV}} value is always lower case. This will cause the lookup to fail. 
- Convert env substring of lookup to title case
**cloudformation/fixtures/templates/elasticip.json**
```
"ElasticIpProdPartnerFtp1": {
"Type": "AWS::EC2::EIP",
"Condition": "EnvIsProd",
"Properties": {
"Domain": "vpc"
}
},
...
"ElasticIpStagingPartnerFtp1": {
"Type": "AWS::EC2::EIP",
"Condition": "EnvIsStaging",
"Properties": {
"Domain": "vpc"
}
},
```
**cf template**
```
"EIPAssociation": {
"Type": "AWS::EC2::EIPAssociation",
"Condition": "IsMultiZone",
"Properties": {
"InstanceId": { "Ref": "Ec2Instance" },
"AllocationId": …
```

fix eip lookups with variable env

---

src/ef_aws_resolver.py

**Ready**
optional number in eip regex validator to account for numbered environments (e.g. proto0)
```
± |eip_lookup_num {2} ?:1 ✗| → python
Python 2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> lookup = "ElasticIpproto0MyService1"
>>> m = re.search('ElasticIp([A-Z]?[a-z]+[0-9]?)\w+', lookup)
>>> env = m.group(1)
>>> print(env)
proto0
>>> lookup = lookup.replace(env, env.title())
>>> print(lookup)
ElasticIpProto0MyService1
```

allow numbers in env name (eg. proto0)

---

doc/symbol-reference.md
src/ef_aws_resolver.py

**Ready**
Allows lookups of subnets beyond the vpc default
- add tagged-route-table-id lookup in ef_aws_resolver
```
"vpnRoutePropagation": {
"Type": "AWS::EC2::VPNGatewayRoutePropagation",
"DependsOn": [ "vpnGateway", "vpnToVpcAttachment" ],
"Properties": {
"RouteTableIds": [ "{{aws:ec2:route-table/main-route-table-id,vpc-{{ENV}}}}", "{{aws:ec2:route-table/tagged-route-table-id,{{ENV}}-test}}" ],
"VpnGatewayId": { "Ref": "vpnGateway" }
}
},
```
```
py-2.7.13 000612-ml in ~/workspace/cde/ellation-formation-c
± |update_routing U:3 ✗| → ../dist/ef-cf cloudformation/fixtures/templates/vpn.json proto0 --verbose --devel
...
"vpnRoutePropagation": {
"Type": "AWS::EC2::VPNGatewayRoutePropagation",
"DependsOn": [ "vpnGateway", "vpnToVpcAttachment" ],
"Properties": {
"RouteTableIds": [ …
```

Route table lookup

---

src/ef-cf.py

**Ready**
ef-cf does not fail on a stack rollback. This results in unexpected behaviour as scripts and pipelines that rely on ef-cf not notifying of the failure.
[OPS-9082](https://ellation.atlassian.net/browse/OPS-9082)
- add a check for `ROLLBACK_COMPLETE` and fail on it
Simple scenario
1. pick a stack with a database;
2. increase the database storage;
3. deploy same stack with smaller database size using ef-cf
4. ef-cf fails with `UPDATE_ROLLBACK_COMPLETE` message; `echo $?` should not be 0

Fail ef-cf on stack rollback OPS-9082

---

doc/setup-and-configuration.md

**Ready**
Updating documentation to use pants version 1.5.0
* Updating documentation to use pants version 1.5.0
Build ef-open using the new pants version 1.5.0

Updating documentation to use pants version 1.5.0

---

src/ef-generate.py

**Ready**
Updated the key policy attached to the service's KMS to allow the default service linked role for autoscaling groups the ability to decrypt amis
[OPS-9597](https://ellation.atlassian.net/browse/OPS-9597)
Updated the ef-generate for kms
None
None
The policy is what I manually pasted into cde proto0

OPS-9597 Update the ef-generate for KMS policy 

---

src/ef_aws_resolver.py
src/ef_utils.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Add feature for ef-open to lookup full kms key arn given the key alias
[OPS-9670](https://ellation.atlassian.net/browse/OPS-9670)
Updated ef_aws_resolver, ef_utils, and unit tests
None
None
Ran the unit tests

OPS-9670 Add feature for ef-open to lookup full kms key arn given the key alias

---

src/ef-generate.py

**Ready**
Fix misquoted KMS policy
[OPS-9885](https://ellation.atlassian.net/browse/OPS-9885)
- add quotes to json-like string for policy
Ran ef-generate on alpha0.

Fix misquoted kms_policy params

---

tests/unit_tests/test_ef_template_resolver.py

**Ready**
Following 2c50ab3, the `test_ef_template_resolver.py` test was failing due to a missing mock in the list of clients.
- add the STS mock to `test_ef_template_resolver.py`

Fix failing template_resolver_test

---

src/ef_utils.py
tests/unit_tests/test_ef_utils.py

**Ready**
While looking into ef-generate failing due to throttling, I profiled the command. The resulting profile has revealed that he command is wasting a lot of time to recreate and reconnect the AWS clients, as a result of constantly calling `resolve_policy_document`.
This PR implements a basic caching mechanism for the `create_aws_clients`. Based on my tests, the caching speeds up ef-generate by a factor of at least 2. See attached profiles for details.
The rationale for caching the clients:
- a session client is a long lived object; there is no need to create new clients per API request
- creating new clients is expensive: every new client initiates a connection to the API,  which take up the bulk of the execution time.
Without client caching: …

Cache aws clients

---

src/ef-instanceinit.py

**Ready**
Instantiate EFTemplateResolver only once, not for every file parameter. This is to avoid the problem for every single template and parameter pair to create an AWS boto3 client and avoid hitting the AWS rate limit for API calls. 
I have yet to understand what the comment means when it states `cached keys`. However from the initial testing, I have not seen a problem with moving this statement above and being reused for every parameter and template pair.
* Instantiate EFTemplateResolver only once, not for every file parameter
```
Loading parameters object: all/parameters/filebeat.yml.parameters.json
Resolving template
Loading template object: all/templates/filebeat.yml
Loading parameters object: all/parameters/filebeat.yml.parameters.json
make directories: /etc/filebeat 755
open: …
```

Instantiate EFTemplateResolver only once, not for every file parameter

---

src/ef-cf.py

**Ready**
Compress Cloudformation template if it exceeds max allowed length.
Compression in this case is to remove whitespaces from the template. The original template remains intact and it is only the rendered template that will be sent to Cloudformation that is compressed. This is to avoid the scenario where our cloudformation template exceeds the length of max allowed template size to be sent over in the API request.
* Remove whitespaces if the Cloudformation template exceeds the max allowed length / size of the template before sending it to Cloudformation.
```
000377-ml:ellation_formation jwong$ ef-cf cloudformation/services/templates/subs.json proto0 --devel
not refreshing repo because --devel was …
```

Compress Cloudformation template if it exceeds max allowed length

---

efopen/ef_cf.py
efopen/ef_generate.py
setup.py

**Ready**
This will temporarily remove calls to the ef_plugin module. This was specifically designed to work with our pants binaries and is no longer functioning since moving away from that pattern. Currently ef-cf and ef-generate can run into issues executing this.
- remove calls to run_plugins from ef-cf and ef-generate
Before..
```
Traceback (most recent call last):
File "/usr/local/bin/ef-cf", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/site-packages/efopen/ef_cf.py", line 301, in main
run_plugins(context, clients)
File "/usr/local/lib/python2.7/site-packages/efopen/ef_plugin.py", line 85, in run_plugins
plugin_module = importlib.import_module("plugins.{}.{}".format(plugin_name, modname))
File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Ver …
```

temporarily remove ef_plugin calls

---

efopen/ef_utils.py

**Ready**
ef_utils.whereami() fails for not having sudo access in CI, when it's trying to call `virt-what` to determine whether it's running on a virtualbox machine.
Since this is not an important edge case, we just catch this exception scenario and return "unknown".

allow virt-what to fail during whereami(), and just return 'unknown' instead of excepting

---

efopen/ef_aws_resolver.py
efopen/ef_template_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Add the ability to look up ELBv2 DNS and hosted zone properties.
[OPS-10777](https://ellation.atlassian.net/browse/OPS-10777)
- add elbv2 dns lookup
- add elbv2 hosted zone lookup
https://github.com/crunchyroll/ellation_formation/pull/3323
`cd ellation_formation`
```
cat > reactions.json << h
{
"Name": "reactions.vrv.co",
"Type": "A",
"HostedZoneId": "{{aws:elbv2:load-balancer/hosted-zone,proto0-reactions-e}}",
"DNSName": "{{aws:elbv2:load-balancer/dns-name,proto0-reactions-e}}"
}
},
{
hh
```
`python ../ef-open/efopen/ef_cf.py reactions.json proto0 --devel --verbose`

Lookup ELBv2 dns-name and hosted-zone

---

doc/symbol-reference.md
efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Adding support for ELBv2 "ARN suffixes" for ALBs and ALB target groups.
This is useful for the weird target-tracking cloud formation autoscaling spec.  Speficially the string-concatted arn suffixes for `ResourceLabel`:
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_PredefinedMetricSpecification.html
run the included unit tests.

adding alb and target group arn suffixes as lookup targets

---

efopen/ef_resolve_config.py

**Ready**
remove bare exception catch that causes ef-resolve-config to always exit successfully

remove bare exception catch

---

efopen/ef_aws_resolver.py

**Ready**
When the parent function calls the child function, and you specify a default value, say a String with a value "NONE", the child function would return that default value. The problem is, the parent function is only checking for None, when the NONE string is not a None type, so it takes that value thinking it's a valid value and looks it up and fails because AWS says WTF are you sending me.
So I've updated the parent function check so that it checks if the value is None or the same value as the default, meaning the lookup failed.
[OPS-10906](https://ellation.atlassian.net/browse/OPS-10906)
Tested locally and in ellationeng

OPS-10906-v2 respect default values for cognito lookups

---

efopen/ef_password.py
tests/unit_tests/test_ef_password.py

**Ready**
fix ef-password to pass tests.
`ef-password --length 10` is technically valid, so making the excluseive set of --secret_file, --decrypt, and --plaintext be required was a bad assumption.

fix ef-password to pass tests.

---

efopen/ef_cf.py

**Ready**
Allow jenkins master to use a profile when calling ef-cf
conditional around setting profile for boto3 session on ef-cf
Faith

use profile on jenkins master

---

efopen/ef_cf.py

**Ready**
Adds json validation to rendered cf template, moves cfn-linting to it's own class, and undo's all the weird 'from os.foo import everything, and, the, kitchen, sink'
Extra comma in template. 
Before:
```
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
```
After:
```
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Failed to decode JSON
ValueError('Expecting property name enclosed in double quotes: line 36 column 5 (char 923)',)
```
Remove extra comma and test lint command:
```
Validation …
```

Cf json linting

---

efopen/ef_resolve_config.py
setup.py

**Ready**
Using `ef-resolve-config --lint` will perform linting if the template is a json or yaml. 
- add lint param and behavior
- fix import order
_Intentionally broken yaml:_
```
± |master {13} S:1 U:1 ✗| → ../ef-open/efopen/ef_resolve_config.py proto0 configs/cr-manga.cron/templates/cr-manga_config.yml --lint
/Users/dlutsch/workspace/ellation_formation/configs/cr-manga.cron/templates/cr-manga_config.yml
1:2       warning  wrong indentation: expected 0 but found 1  (indentation)
6:20      warning  too many spaces after colon  (colons)
7:20      warning  too many spaces after colon  (colons)
8:20      warning  too many spaces after colon  (colons)
9:1       error    trailing spaces  (trailing-spaces)
YAML failed linting process
```
_Intentionally broken JSON:_
```
± |master {13} S:1 ✗| …
```

add --lint param to ef-resolve-config

---

Pipfile.lock

**Ready**
Rebuild Pipfile.lock with `pipenv update`
- Boto3 -> 1.9.77
- botocore -> 1.12.77
- cfn-lint -> 0.11.1
- something added pathspec as a dependency
- pylint -> 1.9.4
- wrapt -> 1.1.3.0

Rebuild Pipfile.lock with `pipenv update`

---

efopen/ef_cf.py
efopen/ef_resolve_config.py

**Ready**
Add --silent param to ef-resolve-config which suppresses rendered template output
```
/Users/dlutsch/.local/share/virtualenvs/ef-open-43I3Cg99/bin/python /Users/dlutsch/workspace/ef-open/efopen/ef_resolve_config.py proto0 configs/cms-imgsrv/templates/nginx.conf --lint --silent
Template is not a yaml or json, skipping lint.
Config template rendered successfully.
Process finished with exit code 0
```

Suppress ef-resolve-config output

---

efopen/ef_template_resolver.py

**Ready**
Inserts a placeholder value of "NONE" for templates where an ami-id lookup has failed. Specifically used for a service that hasn't yet been deployed. Once the template successfully renders we can then run testing against it for CI. 
```
± |test_ef_ci_updates_4 {13} ✓| → ../ef-open/efopen/ef_cf.py cloudformation/services/templates/categories.json prod --devel --lint
not refreshing repo because --devel was set or running on Jenkins
WARNING: No ami-id found for {{version:ami-id,prod/categories}} - placeholder value of 'NONE' used in rendered template
```

allow placeholder string for failed ami lookups

---

efopen/ef_instanceinit.py
efopen/ef_template_resolver.py

**Ready**
Enable ef-instanceinit latebind rendering
* Remove conditional check that assumes that local dev environment will not access AWS resources
* Inserted profile that will be used when we're in the local dev environment
```
Jerrys-Mac-mini:ef-open jwong$ pytest
=========================================================================================================================== test session starts ===========================================================================================================================
platform darwin -- Python 2.7.15, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /Users/jwong/workspace/ef-open, inifile:
plugins: cov-2.6.0
collected 194 items
tests/unit_tests/test_ef_aws_resolver.py ............................................................... …
```

Enable ef-instanceinit latebind rendering

---

efopen/ef_cf.py

**Ready**
Removes hardcoded ignore-checks from the cfn-lint command call. Instead these will be defined in a .cfnlintrc file in the dir that ef-cf is being run in. 
See: https://github.com/awslabs/cfn-python-lint#config-file

remove inline ignore_checks, move to config file

---

efopen/ef_cf.py
efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

**Ready**
ef-cf --percent feature
Add the ability to tweak the max batch size of a particular cloudformation template to speed up (or down) the deployments of a particular service.
* ef-cf --percent feature
* Unit test for new helper function
```
Jerrys-Mac-mini:ef-open jwong$ pytest tests/unit_tests/test_ef_utils.py --cov ef_utils -v --cov-report term-missing --disable-pytest-warnings
========================================================================================================================== test session starts ==========================================================================================================================
platform darwin -- Python 2.7.15, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /usr/local/opt/python@2/bin/python2.7
cachedir: .pytest_cache
rootdir: …
```

ef-cf --percent feature

---

Pipfile.lock

bump dependencies, notably:
- boto3
- botocore
- cfn-lint
- yamllint
**Ready**
ran `pipenv update`.  cfn-lint specifically has been making rapid progress, and its worth staying on top of those changes.

upgrade dependencies

---

efopen/ef_resolve_config.py

**Ready**
Currently, we're linting yaml files before resolving their ef-open values. This leads to false positives, potential misses (in case the resolved variables are not yaml compliant) and developer workarounds.
Also, the PR remove success messages, allowing for piping or redirecting the output in order to obtain a valid config file; e.g `ef-resolve-config prod template.yml > config.yml`
- lint resolved yamls
- print lines that failed linting
- if not `--silent`, print only the template without success messages

Lint resolved configs

---

efopen/ef_cf_diff.py

**Ready**
Treat the environment names as 'short' names, for the purposes of finding named stacks.

only use the 'short' environment names in ef-cf-diff

---

efopen/ef_instanceinit.py

**Ready**
Update ef_instanceinit.py to skip user group errors
[OPS-11530](https://ellation.atlassian.net/browse/OPS-11530)
Local testing in a very ghetto way, the key thing I wanted to make sure is that it wouldn't explode if the ssh folder in the s3 prod configs bucket didn't exist yet, specifically ssh. It still runs fine so far so it should be safe to merge this tool in first and then perform the ellation_formation change later.

OPS-11530 Update ef_instanceinit.py to skip user group errors

---

efopen/ef_cf_diff.py

**Ready**
Per after-merge review on https://github.com/crunchyroll/ef-open/pull/108#discussion_r253470548
Avoid the subprocess call out to `diff` in favor of a native python lib.
It's worth noting that the python diff lib has a slightly crappier diff algorithm than unix `diff`.  It'd be great if python's difflib had an option for a patience diff algorithm or something similar, but it looks pretty basic.
But this will work alright for our purposes.

Replace the string diff implementation with a native python lib, instead of a subprocess call out to a maybe-missing shell command.

---

efopen/ef_resolve_config.py

**Ready**
The json linter chokes on escape characters in strings. This will let them through.
This blocks the ticket below.
[ESS-1598](https://ellation.atlassian.net/browse/ESS-1598)

Make json linting be non-strict to allow for control characters.

---

Pipfile.lock

Changes of note (but not complete):
- pyyaml - 3.13 -> 5.1 - addresses CVE-2017-18342
- cfn-lint - 0.15.0 -> 0.16.0
**Ready**
[OPS-11547](https://ellation.atlassian.net/browse/OPS-11547)
There was a CVE in the previous stable version of PyYAML, but today there was a new version released.

Bump some python dependencies

---

efopen/ef_version.py
tests/unit_tests/test_ef_version.py

**Ready**
Often times it is required to rollback a service to a specific AMI, like a few versions back of some services. 
This PR adds a `--rollback-to` option to `ef-version` to enable re-setting the current version to a version in the history of the service.
[DA-283](https://ellation.atlassian.net/browse/DA-283)
- add a `--rollback-to` flag
- add rollback to an AMI functionality to cmd_rollback
- test cover cmd_rollback
1. Run the unit-tests
For a real-life test, run
```
ef-version --history text playheads ami-id alpha0
```
pick a previous version and use the current code-base to run
```
ef_version playheads ami-id alpha0 --rollback-to <ami-version> --devel --commit
```

DA-283 Rollback to specific version

---

efopen/ef_cf.py

**Ready**
If we use the percent flag when we deploy services that are not in prod, it is possible not to get an actual result. Setting 1 as the max batch size is a safe default as it will allow the service to continue updating even if there was some mistake.
- add safe default for max_batch_size

Add a safe default max batch size

---

Pipfile
Pipfile.lock

**Ready**
Add pylint as a dev dependency, to keep vscode from complaining _ever_ _single_ _time_ I open a python file.
Also bump the dependencies, which notably upgrades the cloudformation lint tool from 0.16.0 to 0.20.1:
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CHANGELOG.md
You can manually update an existing virtual env with --dev dependencies with:
```
pipenv install --dev
```
And if you're using VScode, it'll Just Work.

add pylint as a dev dependency.  Bump all the package dependencies.

---

efopen/ef_config.py

**Ready**
Allow the use of the dist-hash key in ef-version for lambdas. We have been discussing using this to version and distribute lambda's to different environments.
- add "aws_lambda" object type to dist-hash array.

add aws_lambda to dish-hash ef-version key

---

efopen/ef_generate.py
tests/test_data/test_service_registry_1.json
tests/unit_tests/test_ef_generate.py

**Ready**
Note that it only throws a warning if the managed policy doesn't exist, instead of a halting error.  This is to avoid the "can't deploy because the policy doesn't exist yet" scenario.

Add mechanism for linking roles to "Customer Managed" policies (as opposed to just AWS Managed policies)

---

Pipfile
Pipfile.lock

**Ready**
refresh of the pip dependencies, notably bumping to the latest `cfn-lint` version.
Also add `rope` as a dev dependency, to provide functionality for the vscode IDE.  Install the virtualenv with `pipenv install --dev` to get those.

bump pipenv dependencies, add rope as a dev dependency

---

setup.py

to address a failure to publish bug
Turns out, they changed stuff in pypi's codebase:
https://github.com/pypa/warehouse/pull/5835
https://github.com/pypa/warehouse/issues/5890
**Ready**
ef-open has been failing builds on the publish step for a while now, and no one noticed.
https://jenkins-build.ellationeng.cx-mgmt.com/job/ef-open/228/console
Turns out pypi tightened its validation around readme files, of all things.

Add the long description type to the setup.py

---

efopen/ef_site_config.py

**Ready**
On a EC2 machine ef-version outputs and error message when not able to read from ssm. This interferes with our pipeline reading the versions. This is a hotfix, an actual fix for proper error handling and logging will be coming soon.
[OPS-12902](https://ellation.atlassian.net/browse/OPS-12902)
- remove error output when SSM read fails

Remove additional prints in ef-version

---

efopen/ef_template_resolver.py

**Ready**
Allow `*` symbol in ef-open lookup. Example lookup that needs to be resolved: 
```
"{{aws:acm:certificate-arn,us-east-1/*.example.com,NONE}}",
```
* Allow `*` symbol in ef-open lookup
```
Jerrys-Mac-mini:ef-open jwong$ pytest tests/unit_tests/test_ef_template_resolver.py --cov ef_utils -v --cov-report term-missing --disable-pytest-warnings
====================================================== test session starts =======================================================
platform darwin -- Python 2.7.15, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /usr/local/opt/python@2/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/jwong/workspace/ef-open, inifile:
plugins: cov-2.6.0
collected 11 items
tests/unit_tests/test_ef_template_resolver.py::TestEFTemplateResolver::test_context_vars_prot …
```

Allow `*` symbol in ef-open lookup

---

efopen/ef_template_resolver.py

**Ready**
Fix lookup to also work on mgmt.<account_alias>
* Fix lookup to also work on mgmt.<account_alias>
```
Jerrys-Mac-mini:ef-open jwong$ pytest tests/unit_tests/test_ef_template_resolver.py --cov ef_utils -v --cov-report term-missing --disable-pytest-warnings
====================================================== test session starts =======================================================
platform darwin -- Python 2.7.15, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /usr/local/opt/python@2/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/jwong/workspace/ef-open, inifile:
plugins: cov-2.6.0
collected 11 items
tests/unit_tests/test_ef_template_resolver.py::TestEFTemplateResolver::test_context_vars_protected PASSED                  [  9%] …
```

Fix lookup to also work on mgmt.<account_alias>

---

efopen/ef_cf.py
efopen/ef_generate.py
efopen/ef_instanceinit.py
efopen/ef_utils.py
efopen/ef_version.py
tests/unit_tests/test_ef_utils.py

**Ready**
ef-open runs checks in multiple places if it is running inside an ec2 or not; if does, it uses the instance profile.
Jenkins needs to run commands on multiple environments and depends on a credential map defined in ef_site_config.yml. If we tell whereami about Jenkins, ef-open will try to follow the account map instead of blindly using instance credentials.
[OPS-13352](https://ellation.atlassian.net/browse/OPS-13352)
- whereami knows about Jenkins

OPS-13352 Make whereami aware of Jenkins

---

efopen/ef_version.py
tests/unit_tests/test_ef_version.py

**Ready**
Corrected logic for rollback in the scenario of qa deploys and rolling back from a stable deploy
[OPS-13555](https://ellation.atlassian.net/browse/OPS-13555)
Ran unit tests
000460-ml:ellation_formation vfang$ ef-version --history text test-instance ami-id staging
staging-test-instance ami-id
ami-0dec43a8ae0965b7f 56 test-instance=fb64f9486ab13df6cf482bde328fb45b1b4dd211,pipeline=ab8b9aebd22e8cdf454fa8bc2e3412177e614de0 2019-09-06T23:57:24UTC arn:aws:sts::366843697376:assumed-role/global-role-devops-team/botocore-session-1567814234 1f0Bq_ptpNX..xHHZweR_IExxksvYF4p  stable
ami-03691cfbb177fc240 57 test-instance=0031fce3a33d324946cfaf4ac1fcac6c194e5bd9,pipeline=ab8b9aebd22e8cdf454fa8bc2e3412177e614de0 2019-09-06T07:46:47UTC arn:aws:iam::366843697376:user/vfang …

OPS-13555 Update rollback logic for ef-version

---

efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

**Ready**
The code changes in #128 failed to account for the CI running in Jenkins, generating a number of false negatives on the unit-test level. This PR fixes that.
https://jenkins-build.ellationeng.cx-mgmt.com/job/ef-open/242/console
- override the Jenkins environment in tests

Fix whereami tests

---

efopen/ef_cf.py
efopen/ef_generate.py
efopen/ef_version.py

**Ready**
[OPS-13631](https://ellation.atlassian.net/browse/OPS-13631)
Unexpected behavior occurred when we pushed out ef-open release 0.13.5. This PR aims to fix the issues with the whereami jenkins introduced as well as clear up the hard to read conditions
Tested ef-cf, ef-generate, ef-version on my machine using PyCharm to mimic that it's a Jenkins Machine with the JENKINS_URL env var

OPS-13631 Fix logic so that ef-open tools behave correctly on Jenkins and elsewhere

---

efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

**Ready**
[OPS-13637](https://ellation.atlassian.net/browse/OPS-13637)
Update ef-open so that it still looks for a credentials file on regular jenkins and instance role on jenkins docker

OPS-13637 Fix ef-open to work with docker

---

efopen/ef_generate.py

**Ready**
allow managed job functions to be used in the aws_managed_policies array
```
± |master {2} U:1 ✗| → python2 ../ef-open/efopen/ef_generate.py global.ellationeng --commit --verbose
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
env: global
env_full: global.ellationeng
env_short: global
aws account profile: ellationeng
aws account number: 366843697376
service: role-sto-standard-access-etpv1 in env: global
Load policy: assume_role_trust_ellationiam from file: /Users/dlutsch/workspace/ellation_formation/policy_templates/assume_role_trust_ellationiam.json
pre-resolution policy template:
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::190231206472:root"
},
"Action": "sts:AssumeRole"
}
]
} …
```

allow managed job functions to be used in the aws_managed_policies array

---

efopen/ef_aws_resolver.py
efopen/ef_context.py
efopen/ef_generate.py
efopen/ef_service_registry.py

**Ready**
`dict.has_key(x)` is being discouraged since [PEP-290](https://www.python.org/dev/peps/pep-0290/#testing-dictionary-membership) and removed in Python 3 completely in favour of `x in dict` - https://docs.python.org/3.0/whatsnew/3.0.html#builtins

Refactor has_key method calls

---

efopen/ef_template_resolver.py

**Ready**
[OPS-13901](https://ellation.atlassian.net/browse/OPS-13901)
Updated the symbol matching used by EFTemplateResolver to allow for an optional leading dot. eg. {{foo}} and {{.foo}} are both allowable lookups, and will resolve "foo": "bar" in the parameters JSON. 
Since I was modifying this code anyway I also updated the regex searches to use a pre-compiled regex string for faster lookups.
Tested using configs/test-instance/templates/config.json with the prod env and modified one of the two symbols to use a leading dot.
template:
```
{
"secret": "{{.secret}}",
"threads": "{{thread_count}}"
}
```
parameters:
```
"prod": {
"secret": "{{aws:kms:decrypt,AQICAHgKKKY71tobDHsDpqGJpxUVx1IxoYgan68yJy9Qn2fHfQEp9aOMyaNg8LlOwWTr1q10AAAAijCBhwYJKoZIhvcNAQcGoHoweAIBADBzBgkqhkiG9w0BBwEwHgYJYIZIAWU …
```

Update EFTemplateResolver Symbol Matching

---

efopen/ef_aws_resolver.py

**Ready**
Currently, KMS-encrypted strings are evaluated one time less than non-encrypted strings by ef-instanceinit. This will normalize the behavior between the two.

normalize encrypted string behavior in ef_instanceinit

---

efopen/ef_cf.py
efopen/ef_conf_utils.py
efopen/ef_config.py
efopen/ef_generate.py
efopen/ef_password.py
efopen/ef_service_registry.py
getting-started/ef_site_config.yml
tests/unit_tests/test_ef_conf_utils.py

**Ready**
I can close this PR if anyone can give me a valid reason why we care about checking the repo. As it is the current regex is causing ef-cf to fail if the repo was not cloned with the ".git" suffix. But really, what are we trying to protect against here?
```
/Users/dlutsch/.local/share/virtualenvs/ef-open-43I3Cg99/bin/python /Users/dlutsch/workspace/ef-open/efopen/ef_cf.py cloudformation/services/templates/data-dbclient.json prod --lint
=== CLOUDFORMATION LINTING ===
W3005 Obsolete DependsOn on resource (ExternalElasticLoadBalancer), dependency already enforced by a "Fn:GetAtt" at Resources/PublicDns/Properties/RecordSets/0/AliasTarget/HostedZoneId/Fn::GetAtt/['ExternalEl …
```

remove pointless repo validation

---

Pipfile.lock

**Ready**
Updating Pipfile.lock to pull in newest cfn-lint
* Update pipfile.lock file by running `pipenv --update`
Ran pytest and tested out lint on failing CI test.

Updating Pipfile.lock to pull in newest cfn-lint

---

doc/symbol-reference.md
efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Add the ability to look up VPN Gateway ID.
[OPS-14174](https://ellation.atlassian.net/browse/OPS-14174)
- add VPN Gateway ID lookup
https://github.com/crunchyroll/ellation_formation/pull/5703
`python ../ef-open/efopen/ef_cf.py vpn-md.json proto0 --devel --verbose`
```
...
"vpnToVpcAttachment": {
"Type": "AWS::EC2::VPCGatewayAttachment",
"Properties": {
"VpcId": "vpc-3939795d",
"VpnGatewayId": "vgw-e021f8fe"
}
}

Add vpn-gateway-id lookup in ef_aws_resolver

---

.gitignore
.vscode/settings.json
efopen/ef_generate.py

**Ready**
Fix newrelic executor error
[OPS-14184](https://ellation.atlassian.net/browse/OPS-14184)
- remove newrelic.executor module
Before:
```
$ ef-generate staging --commit --dev
...
File "/usr/local/bin/ef-generate", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/site-packages/efopen/ef_generate.py", line 642, in main
create_newrelic_alerts()
File "/usr/local/lib/python2.7/site-packages/efopen/ef_generate.py", line 557, in create_newrelic_alerts
from newrelic.executor import NewRelicAlerts
ImportError: No module named newrelic.executor
```
After:
```
$ ef-generate staging --commit --dev
...
Exit: success
```

Fix newrelic executor error

---

efopen/ef_cf.py
efopen/ef_generate.py
efopen/ef_password.py
efopen/ef_version.py
efopen/ef_version_resolver.py
efopen/test-template.txt
tests/unit_tests/test_ef_conf_utils.py
tests/unit_tests/test_ef_utils.py
tests/unit_tests/test_ef_version.py

**Ready**
The `message` attribute on the Exception classes was deprecated in Python 2.5 and removed completely for Python 3. In order to port to Py3, we need to get rid of any Exception.message calls.

Remove Exception.message attribute access

---

doc/symbol-reference.md

**Ready**
[OPS-13751](https://ellation.atlassian.net/browse/OPS-13751)
Updated documentation on symbol substitutions

OPS-13751 update doc on symbol references and how to avoid {{{ }}} errors

---

efopen/ef_generate.py

**Ready**
[OPS-14226](https://ellation.atlassian.net/browse/OPS-14226)
Fixes Newrelic alert creation. Previously this import statement was `from newrelic.executor import NewRelicAlerts` which worked locally because I had the repo in my python path, but not for anyone else. This should fix the error by including the parent module in the import path.

readd newrelic alerts, fix import statement

---

efopen/ef_generate.py

**Ready**
[OPS-14161](https://ellation.atlassian.net/browse/OPS-14161)
In order to avoid the multiple encryption steps for a service with subservices, we will allow subservices to decrypt secrets encrypted with the main service's key.

OPS-14161 Allow subservices to decrypt main service secrets

---

.travis.yml

**Ready**
We're not running any CI on ef-open since it's a public repo and anybody can botch our Jenkins pipelines. Why not make us of Travis, which allows free CI for open source project?
We need to setup a Travis.ci account, but the rest is quite simple.
e.g: https://travis-ci.com/momoneko/ef-open

Add a travis.ci file

---

.travis.yml

**Ready**
Due to a strange issue with Python's setup-tools, running `python setup.py install` does not resolve the correct version of `zipp` for Python2, failing the build. This might be related to Python 2 getting deprecated.
`pip` seems to work fine, so switching to it for the installation.

Use pip to install on travis

---

doc/symbol-reference.md
efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

> Valid states are:
> Ready - This PR is ready to be reviewed.
> Not Ready - Please provide an explanation below.
**Ready**
[ESS-2498](https://ellation.atlassian.net/browse/ESS-2498)
> A description of the motivation and implementation of this PR.
> Include any relevant details like:
> - Test results
> - Unusual deployment requirements
> - Current deployed state, if any
> - General issues for discussion during the review
In order to limit traffic to a private API Gateway, I would like to be able to specify which VPC endpoint is allowed to talk to it. Unfortunately, this requires specifying the VPC endpoint ID in the API Gateway resource in CloudFormation, and `ef-open` does not have a method for doing so. This PR adds that method.

Add ability to get vpc endpoint ids in AWS resolver

---

doc/symbol-reference.md
efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

> Valid states are:
> Ready - This PR is ready to be reviewed.
> Not Ready - Please provide an explanation below.
**Ready**
[ESS-2498](https://ellation.atlassian.net/browse/ESS-2498)
> A description of the motivation and implementation of this PR.
> Include any relevant details like:
> - Test results
> - Unusual deployment requirements
> - Current deployed state, if any
> - General issues for discussion during the review
As it turns out, while AWS did add support for tags for VPC endpoints, you can only add them through the EC2 API / console. CloudFormation currently does not support it, though it is on their roadmap (https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/projects/1).
As such, we needed a new way to find a specific VPC endpoint. We reasoned that we are …

Add ability to get VPC endpoint ID by VPC name and Service name

---

efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

**Ready**
During the setup for checking the encryption key, I copy pasted from the `kms_key_arn` function and didn't run through all of the test cases.

Fix error handling for missing KMS aliases

---

efopen/ef_generate.py
efopen/newrelic_executor.py

**Ready**
[OPS-14634](https://ellation.atlassian.net/browse/OPS-14634)
Implemented the `ef-generate` feature to create Cloudfront Alert policy in NewRelic for `prod` environment. 
This differs from service alert policy because all Cloudfront distributions are placed under one NewRelic Alert policy and for each CF distribution ef-generate creates 2 conditions:
* 4xx errors
* 5xx errors
For reference, I've used VOD CloudFront conditions. 
Alert policy created https://alerts.newrelic.com/accounts/1354009/policies/674807

OPS-14634 Create CloudFront alerts in NewRelic

---

.circleci/config.yml

**Ready**
[OPS-14927](https://ellation.atlassian.net/browse/OPS-14927)
Disable pylinting because it runs with disabled for many coding convention errors

Disable pylint in CircleCI

---

efopen/ef_aws_resolver.py
efopen/ef_config.py
efopen/ef_generate.py
efopen/ef_template_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
[OPS-14807](https://ellation.atlassian.net/browse/OPS-14807)
Implement the functionality for parsing the following syntax, in order to support ECS in ETPv1:
`{{aws:ecr:repository/image-name,{{ENV}}-{{SERVICE}}-ecr}}`
Any improvements are welcome.
Automated tests implemented and deployment made using this version of ef-open

OPS-14807 Implement repository parsing by service name

---

efopen/ef_generate.py

**Ready**
ef-generate currently doesn't accept multiple principals in its default policy template. Fixing so it accepts lists.
Also, slight cleanup by making the policy template be a dict instead of a hand built string.

Make ef-generate accept multiple principals in policy

---

efopen/newrelic_executor.py

[OPS-15043](https://ellation.atlassian.net/browse/OPS-15043)
with the additional of a new field, there's a chance for the ef-open code to blow up if the dictionary key isn't there
Should instead do a safe lookup and if there's nothing there, nothihng bad happens with ef-generate calling newrelic_executor

OPS-15043-v2 Safe lookup for new relic settings

---

efopen/ef_generate.py

**Ready**
[OPS-15098](https://ellation.atlassian.net/browse/OPS-15098)
Refactored how managed policy arns are retrieved. Needed to do this because we added another policy prefix (/service-role/) to search.

OPS-15098 update how managed policy arns are retrieved

---

efopen/ef_password.py
tests/unit_tests/test_ef_password.py

**Ready**
[OPS-15202](https://ellation.atlassian.net/browse/OPS-15202)
There was an issue with ef-password such as when called from bash in the form `ef-password --plaintext "hello\nworld"` the OS transforms the plaintext argument into `"hello\\nworld"`, resulting in unexpected results on decryption
The most proeminent issue is that on decryption `hello\nworld` resolves as `hello\nworld` instead of 
```
hello
world
```

OPS-15202 Unescape escaped sequences in args

---

.github/PULL_REQUEST_TEMPLATE.md
efopen/ef_generate.py
tests/unit_tests/test_ef_generate.py

[OPS-15109](https://ellation.atlassian.net/browse/OPS-15109)
Update ef-generate to enable KMS key rotation
Updated the ef-generate unit tests to check that enable_key_rotation is always called
Update the pull request template

OPS-15109 Update ef-generate to enable KMS key rotation

---

efopen/ef_generate.py

**Ready**
[OPS-15209](https://ellation.atlassian.net/browse/OPS-15209)
Add aws_ecs and aws_ecs_http services types to handle ecs deployments with and without albs, respectively.
**Testing**
Deployed proto0-test-container stack using aws_ecs_http service type.

OPS-15209 Add aws_ecs and aws_ecs_http service types

---

efopen/ef_config.py

Update the 'image-tag' ef-version key to support the newer aws_ecs and aws_ecs_http types

update allowed_types for image-tag version key

---

efopen/ef_generate.py

Only create newrelic alerts with ef-generate if the "newrelic" key exists under plugins in ef_site_config.yml

conditionally create newrelic alerts

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-15344](https://ellation.atlassian.net/browse/OPS-15344)
Couple of issues with the cloudfront cod
- condition names that were created didn't match what it was checking if it didn't exist or not, so for cloudfront it kept always creating alert conditions til it hit the 500 limit, so named it so it would match
- the get call in newrelic_interface for GET would not handle the response correctly with prod-cloudfront, the links is inside the response string, not a separate field in the dict object. This only occurs calling cloudfront, the other alerts work as expected
- 'select_value': 'provider.{}.Average'.format(error_rate), line 93 in newrelic_executor is an invalid value, need to look up what the correct value is

OPS-15344 make ef-generate working for prod without cloudfront

---

efopen/ef_template_resolver.py
efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

[MORT-1148](https://ellation.atlassian.net/browse/MORT-1148)
Removes the ec2.describe-instance api calls being made during instance boot. We've seen this get throttled by the aws api during large scaling events, which then causes ef-init to fail. 
Deleted ef_utils.get_instance_aws_context and associated tests as it is not used anywhere in the code.
For the purposes of code review, here is an example profile_arn `"arn:aws:iam::366843697376:instance-profile/staging-test-instance"`
Tested by manually modifying the ef-open code on a proto0-test-instance machine due to the requirements around running on an actual ec2 instance rather than locally.

MORT-1148 remove ec2.describe-instance api calls

---

efopen/ef_template_resolver.py

Fixes a bug with the `SERVICE` symbol introduced in PR https://github.com/crunchyroll/ef-open/pull/185 
Sample `profile_arn` : `arn:aws:iam::366843697376:instance-profile/staging-test-instance`
Made changes locally on a proto0 test-instance and re-ran ef-init. Specifially looking for usage of the `SERVICE` symbol

fix service symbol on ec2

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-15355](https://ellation.atlassian.net/browse/OPS-15355)
The root cause was that fetching all alert conditions was not correctly implemented. Currently, the link provided by alert conditions GET request does not work anymore so using params to adjust offset seems to be a better solution.
Besides that, the NewRelic documentation states([link](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-cloudfront-monitoring-integration#metrics)) that we can use:
* `4xxErrorRate`
* `5xxErrorRate`
But their UI is not behaving properly and these metric keys are not correct. Had to look into their HTML page to fix this issue.
Also, optimized `create_infra_alert_conditions` method to avoid iteration over `policy.remote_conditions` for each …

OPS-15355 Fix Cloudfront alerts creation

---

efopen/newrelic_executor.py

[OPS-15195](https://ellation.atlassian.net/browse/OPS-15195)
Add functionality of creation NewRelic alert policies and conditions for ECS services. Added code should use `ecs_alert_conditions` from `ef_site_config.yml` which is different than default alert conditions. 
This functionality should also ignore creation of alert policies for other aws_fixtures.
https://alerts.newrelic.com/accounts/1354009/policies/778423

OPS-15195 Implement custom alert policies for ECS services

---

efopen/newrelic_executor.py

Services teams only want to be paged for events occurring in production and not alpha/proto/staging

only page teams for ellation account services

---

efopen/ef_generate.py

OPS-15630 In order to allow session manager users to log with dev username on ec2, I need ef-generate to support tags when creating IAM roles
Added support for optional tags in ef-generate

Ops 15630 - In order to allow session manager users to log with dev username on ec2, I need ef-generate to support tags when creating IAM roles

---

efopen/ef_aws_resolver.py
efopen/ef_template_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

**Ready**
Support AWS DynamoDB Stream ARN lookup
* Added `dynamodb:stream-arn,...` lookup base on the DynamoDB Table name
* Added unit-tests associated with this lookup
* Sort some values in lexical order
```
000939-ml:ef-open jwong$ pytest tests/
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 2.7.15, pytest-3.7.2, py-1.5.4, pluggy-0.7.1
rootdir: /Users/jwong/workspace/ef-open, inifile:
plugins: cov-2.5.1
collected 241 items
tests/unit_tests/test_ef_aws_resolver.py ...................................................................................................                                             [ 41%] …
```

Support AWS DynamoDB Stream ARN lookup

---

efopen/ef_config.py

OPS-15824
Lambdas are going to be versioned with the commit-hash key and version-number in the ellation_formation templates.

OPS-15824 Add commit-hash key for lambdas

---

efopen/ef_cf.py

Add render flag to ef-cf. Use to cleanly output a rendered cloudformation template. Can be used to write to disk or programmatically load output into a json object.

ef-cf --render

---

efopen/ef_context.py

Fixing bug related to this new ef-generate arg
```
± |master {10} ✓| → ef-generate global.codemobs --commit --only_for role-dev-codemobs
Traceback (most recent call last):
File "/usr/local/bin/ef-generate", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/site-packages/efopen/ef_generate.py", line 636, in main
CONTEXT = handle_args_and_set_context(sys.argv[1:])
File "/usr/local/lib/python2.7/site-packages/efopen/ef_generate.py", line 149, in handle_args_and_set_context
context.only_for = parsed_args["only_for"]
AttributeError: can't set attribute
```
```
/Users/dlutsch/.local/share/virtualenvs/ef-open-43I3Cg99/bin/python /Users/dlutsch/workspace/ef-open/efopen/ef_generate.py proto0 --commit --devel --only manga-ftp
Not refreshing repo because --devel was set or running …
```

add missing setter for the context.only_for property

---

efopen/ef_password.py
tests/unit_tests/test_ef_password.py

Adding a flag to enable encrypting escaped sequences for latebind v1.
https://github.com/crunchyroll/ef-open/releases/tag/1.25.0 switched the encryption escape method so that escaped sequences rendered as expected (e.g. `\n` renders as a newline) in latebindb2.
This means that encrypting for latebindv1 with escapes was no longer possible.

Add flag for lbv1 style escapes in ciphertexts

---

efopen/ef_version.py
tests/unit_tests/test_ef_version.py

[OPS-15147](https://ellation.atlassian.net/browse/OPS-15147)
The purpose of getting rid of the flag is that we've seen cloudformation complete but old instances with the old ami-id are still active. When ef-version is run without the noprecheck, even though cloudformation says it's done, ef-version will error saying something went wrong, because the old instances are up. But those old instances will eventually self terminate.
The precheck flag causes more problems than it solves now.
I have to leave the flag in the command line but it won't do anything now. If I remove it now, the python binary complains about being supplied a flag that doesn't exist, and many of our jenkins jobs have that hard coded right now.
TESTS

OPS-15147 get rid of precheck flag

---

efopen/newrelic_executor.py

[OPS-16049](https://ellation.atlassian.net/browse/OPS-16049)
Adjust ef-open to communicate with NewRelic API with REST keys associated to specific AWS environments
Ran a simple ef-generate for specific envs and it used correct values specified in `ef_site_config.yml`

OPS-16049 Use separate newrelic keys for REST API calls

---

efopen/ef_generate.py
efopen/newrelic_executor.py

[OPS-16006](https://ellation.atlassian.net/browse/OPS-16006)
Currently ef-generate is failing in Ellation prod due to the following 3 services having an empty string in their team_opsgenie field: prod-cr-web.admin, prod-cr-web.cms, prod-cr-web.support.
The reason this field is empty is due to the explanation in this PR, crunchyroll/ellation_formation#7904
Because of this, ef-generate errors because it can't add an opsgenie_team of an invalid value, empty string.
To address this, we're implementing the ability for the team to add a alert overrride in the service registry, opsgenie_enabled, that can be set to false. What this does is make it so in the alert policies' notification, the opsgenie team will not be added.
I've looked into using this feature, New Relic muting to see if this would …

OPS-16006 Add alert override to disable opsgenie for a service in service_registry.json

---

efopen/newrelic_executor.py

[OPS-16150](https://ellation.atlassian.net/browse/OPS-16150)
The newrelic response object contains fields that don't exist in our request object. Rather than evaluating equality between these two objects, instead evaluating only the fields we actually care about.

OPS-16150 fix equality check for nrql alert conditions

---

efopen/newrelic_executor.py

N/A
Optimize NewRelic APM condition comparison as terms come in a different order from API and `ef_site_config.yml` has a specific order so comparing remote dictionary with the local one, the comparison is not consistent.
Sometimes, NewRelic API returns `terms` array with `warning` priority as first element, but this is not consistent.
Example:
```
-------------- ef_site_config.yml ------------
instance_init_failure:
name: instance_init_failure
enabled: false
value_function: sum
violation_time_limit_seconds: 3600
terms:
- duration: "5"
operator: above
priority: critical
threshold: "0"
time_function: any
- duration: "5"
operator: above
priority: warning       /// WARNING
threshold: "0"
time_function: any
------------- response from NewRelic REST API ---------
instance_init_failure:
name: …
```

Sort terms array in order to perform correct comparison

---

efopen/ef_password.py

[OPS-16054](https://ellation.atlassian.net/browse/OPS-16054)
- ef-password should do a check on the plaintext value of a secret before encrypting it and ensure that certain special characters are not present. If they are, ef-password should return an error.
- A user can override this behavior by passing in a flag. something like `--special-character-override` or some such.

OPS-16054-Disallow_some_characters_in_ef-password

---

efopen/newrelic_executor.py
efopen/newrelic_interface.py

[OPS-16150](https://ellation.atlassian.net/browse/OPS-16150)
Add better logging to ef-generate when errors to calls for creates or puts to new relic occurs.
Currently the requests.raise_for_status is useless in telling the reasons why it failed and just causes the program to error out.

OPS-16150 Output errors for why calls to new relic fails

---

efopen/newrelic_executor.py

[OPS-16324](https://ellation.atlassian.net/browse/OPS-16324)
This PR addresses the error ef-generate is running into:
`20:13:13 > Creating NewRelic Alerts
20:13:13 Traceback (most recent call last):
20:13:13   File "/bin/ef-generate", line 13, in <module>
20:13:13     sys.exit(main())
20:13:13   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/efopen/ef_generate.py", line 728, in main
20:13:13     create_newrelic_alerts()
20:13:13   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/efopen/ef_generate.py", line 631, in create_newrelic_alerts
20:13:13     NewRelicAlerts(CONTEXT, CLIENTS).run()
20:13:13   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/efopen/newrelic_executor.py", line 375, in run
20:13:13     self.update_application_services_policies()
20:13:13 …

OPS-16324 Fix error in logic that is causing a key lookup in dict to fail with ef-generate

---

efopen/ef_config.py
efopen/ef_version.py

[OPS-16623](https://ellation.atlassian.net/browse/OPS-16623)
Added ability for ef-version to store an additional metadata item for the pipeline build number

OPS-16623 add pipeline build number option

---

.github/PULL_REQUEST_TEMPLATE.md

N/A
Since we have auto-link references, there's no point in having potentially obsolescent and wrong links in the PR template.
e.g OPS-123 vs [OPS-123](https://ellation.atlassian.net/browse/OPS-321)

Update the PR template ticket section

---

setup.py

recent updates to ef-version require an updated version of the boto3 library. works with the current version 1.17.112

update boto3 version requirements

---

efopen/ef_aws_resolver.py
efopen/ef_generate.py

OPS-17701
Update ef-generate to create internal and external blackhole target groups for all http_service's
Choosing to do this in all environments rather than prod only for the following reasons:
1. Parity between prod & non-prod
2. Removes the need to create conditionals in the service cloudformation template around attached target groups
2. Target groups are free, why not?
- Shortend "blackhole" to "bh" due to 32 character limit for target groups. 
- Checking for a new "short_name" field in the service registry entry due to the above mentioned limit
- Set blackhole target group port to 8080 so there there is never any confusion about putting actual service instances in there
```
± |blackhole {20} ✓| → python2 ../ef-open/efopen/ef_generate.py proto0 --devel --commit --only_for …
```

OPS-17701 add blackhole target group creation

---

efopen/ef_generate.py

OPSOC-981
**Ready**
Fix indentation so SGs are being created in non-global environments only.
- partially revert the changes made in https://github.com/crunchyroll/ef-open/pull/230/files#diff-1e70b214a287c01c35da1669f3cecc2616e6f7e0bb7d90a619996ffaadf2dde0R755-R756, after that `ef-generate` should create security groups conditionally in non-global environments only.
https://jenkins-build.ellationeng.cx-mgmt.com/job/ef-generate/7567/console
```
21:18:28 Error: could not get VPC by name: vpc-global
21:18:28 Not refreshing repo because --devel was set or running on Jenkins
21:18:28 env: global
21:18:28 env_full: global.ellationeng
21:18:28 env_short: global
21:18:28 aws account profile: ellationeng
21:18:28 aws account number: 366843697376
21:18:28 Create security group: …
```

OPSOC-981 Fix indentation so SGs are being created

---

efopen/ef_aws_resolver.py
efopen/ef_template_resolver.py

OPS-17854
Create lookups for the following wafv2 resources: 
- IPset
- Rulegroup
- Webacl
One thing to note is that wafv2 cloudfront lookups require a client in the us-east-1 region, which is a new pattern for ef-open. I've created this special regional client and added it to the client array. In the unlikely event that we start using wafv2 for ALBs inside ef-open, this will need to be modified slightly. 
Created the following test cloudformation template: 
```
{
"AWSTemplateFormatVersion": "2010-09-09",
"Description": "test-wafv2-lookups",
"Parameters": {
"RuleGroup": {
"Type": "String",
"Default": "{{aws:wafv2:rule-group-id,global-OfficeViaCloudflare}}"
},
"IpSet": {
"Type": "String",
"Default": "{{aws:wafv2:ip-set-id,global-OfficeCidr}}"
},
"WebAcl": {
"Type": "String",
"Default": …
```

OPS-17854 add wafv2 lookups

---

efopen/ef_utils.py
tests/unit_tests/test_ef_utils.py

OPS-17910
Production deployments using `--percent` to scale based on current desired count started performing very slowly. @AlexBantiuc has noticed that these started deploying with a max batch size of 1 and were reporting a missing current desired count.
```
+ ef-cf ./cloudformation/services/templates/service.json prod --commit --poll --percent 10
Modifying deploy rate to 10%
Service prod-service [current desired: missing, calculated max batch size: 1] 
```
https://github.com/crunchyroll/ef-open/pull/59 has added a performance improvement in the way of caching the AWS clients instead of recreating them each time a part of ef-open needs them. This worked fine, for a while.
https://github.com/crunchyroll/ef-open/pull/233 uncovered a flaw in the implementation of the caching, where the …

OPS-17910 Prevent cache clients from being "poisoned"

---

efopen/ef_cf.py

[OPS-19368](https://jira.tenkasu.net/browse/OPS-19368)
> This change enables the possibility to add tags in the service registry. This tags will apply as stack-level tags [stack-level tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html).
> Both Key and Value support templating, so you can add a tag like this:
```
{"Key": "env", "Value": "{{ENV}}"}
```
[Check this to see an example.
](https://github.com/crunchyroll/ellation_formation/blob/afabc67e37ca37a592fcf0d1843021be0615ea30/service_registry.json#L3746)

Add support to Stack level tags in service_registry [DO NOT MERGE]

---

efopen/ef_aws_resolver.py
efopen/ef_template_resolver.py

OPS-19456
Create lookup to retrieve the ARN of a secret in secretsmanager. This is useful because the secret arn contains a suffix with 6 random characters, so it's not something that we can construct ourselves in the cloudformation template. 
Tested locally using https://github.com/crunchyroll/ellation_formation/blob/master/cloudformation/services/templates/spp-card-auth-canceler.json#L8 and was able to retrieve and insert the arn when using the lookup `{{aws:secretsmanager:secret-arn,datadog-api-key-ctp-services}}`

OPS-19456 add secretsmanager secret lookup

---

.github/workflows/gitleaks.yml
efopen/ef_aws_resolver.py
tests/unit_tests/test_ef_aws_resolver.py

[PLAT-500](https://jira.tenkasu.net/browse/PLAT-500)
Checkout also pr #11584
Update ef_cf to only search for public subnets. The reason for this change is that we are planning to create new private subnets. Right now only public subnets exists, and when we create the new subnets things will be deployed in the new subnets and break. The solution for this is to modify ef_open to only retrieve public subnets. 
i tested in proto0.

Update subnets resolver to search only public subnets

---

efopen/ef_cf.py

I found a bug with the implementation for the --use-high-load parameter. This fixes this problem.
Timeframe/Conditions:
This was tested locally

Fix bug with use-high-load paramter

---

efopen/ef_aws_resolver.py

[REDA-632](https://jira.tenkasu.net/browse/REDA-632)
The `ellation` account now has 147 certificates in it, so this is no longer sufficient.
- Type of change
Timeframe/Conditions:
- Describe the tests you ran to verify your changes.
- Test environment (e.g. local, staging, proto0)

Fix: Allow ACM lookups beyond 100 certs

---

efopen/ef_aws_resolver.py

[REDA-632](https://jira.tenkasu.net/browse/REDA-632)
This failed when requesting the second page in prod. This PR changes how the kwargs are applied to the list_certificates call.

Fix error when there is no next-token
